-- Final content polish for live database. Idempotent; no import/reset.
START TRANSACTION;

UPDATE organization_translations
SET professional_notes = ''
WHERE professional_notes = 'Demo-informatie; inhoud en verwijscriteria moeten voor lancering worden bevestigd.';

UPDATE organization_profile_answers
SET answer_text = ''
WHERE answer_text = 'Demo-informatie; inhoud en verwijscriteria moeten voor lancering worden bevestigd.';

UPDATE organizations
SET status = 'archived',
    visibility_public = 0
WHERE external_key IN ('org_rebound', 'org_tabitha');

UPDATE organization_translations SET name = 'Expertisecenter Onderwijs en Zorg (EOZ)' WHERE organization_id = (SELECT id FROM organizations WHERE external_key = 'org_eoz') AND language_code IN ('nl','pap','en','es');

UPDATE organization_profile_answers SET answer_text = 'Expertisecenter Onderwijs en Zorg (EOZ)' WHERE organization_id = (SELECT id FROM organizations WHERE external_key = 'org_eoz') AND audience_code = 'professional' AND group_key = 'general' AND field_key = 'organisation_name' AND language_code = 'nl';

DELETE ok
FROM organization_keywords ok
JOIN organizations o ON o.id = ok.organization_id
WHERE o.external_key = 'org_eoz'
  AND ok.language_code = 'nl'
  AND ok.keyword = 'Expertise Onderwijs en Zorg (EOZ)';

CREATE TEMPORARY TABLE IF NOT EXISTS tmp_profile_polish (external_key VARCHAR(120), audience_code VARCHAR(32), group_key VARCHAR(80), field_key VARCHAR(120), language_code VARCHAR(8), answer_text LONGTEXT);
TRUNCATE tmp_profile_polish;
INSERT INTO tmp_profile_polish (external_key, audience_code, group_key, field_key, language_code, answer_text) VALUES
('org_rosa_di_sharon','youth','','partners','nl','KHF werkt samen met ZJCN, MHC, Akseso, EOZ en scholen.'),
('org_guana_chat_918','youth','','who_we_are','nl','Guana Chat 918 is een gratis en anonieme hulplijn voor kinderen en jongeren.'),
('org_guana_chat_918','youth','','who_for','nl','Voor kinderen en jongeren die ergens mee zitten, zich zorgen maken of iemand nodig hebben om mee te praten.'),
('org_guana_chat_918','youth','','what_help','nl','Je kunt bellen als je verdrietig, bang, boos of onzeker bent, als er thuis of op school iets speelt, of als je gewoon met iemand wilt praten.'),
('org_guana_chat_918','youth','','how_to_access','nl','Bel gratis en anoniem naar 918.'),
('org_guana_chat_918','youth','','how_we_help','nl','Je krijgt iemand aan de lijn die naar je luistert en met je meedenkt.'),
('org_guana_chat_918','youth','','duration','nl','Een gesprek duurt zolang als nodig is binnen het contactmoment.'),
('org_guana_chat_918','youth','','partners','nl',''),
('org_guana_chat_918','youth','','contact','nl','Bel 918. Website: https://guanachat918.com/'),
('org_guana_chat_918','professional','general','organisation_name','nl','Guana Chat 918'),
('org_guana_chat_918','professional','general','short_description','nl','Guana Chat 918 is een gratis en anonieme hulplijn voor kinderen en jongeren in Caribisch Nederland.'),
('org_guana_chat_918','professional','general','target_group','nl','Kinderen en jongeren.'),
('org_guana_chat_918','professional','general','support_offer','nl','Telefonische, gratis en anonieme ondersteuning voor kinderen en jongeren die iemand willen spreken.'),
('org_guana_chat_918','professional','referral','when_appropriate','nl','Wanneer een kind of jongere behoefte heeft aan een laagdrempelig, anoniem gesprek.'),
('org_guana_chat_918','professional','referral','criteria','nl','Geen formele verwijscriteria.'),
('org_guana_chat_918','professional','referral','indications_required','nl','Nee. Jongeren kunnen zelf bellen.'),
('org_guana_chat_918','professional','practical','contact_details','nl','Bel 918. Website: https://guanachat918.com/'),
('org_kpcn','youth','','who_we_are','nl','Korps Politie Caribisch Nederland (KPCN) is de politie voor Bonaire, Saba en Sint Eustatius.'),
('org_kpcn','youth','','who_for','nl','Voor iedereen die direct gevaar ziet, zich onveilig voelt of dringend politiehulp nodig heeft.'),
('org_kpcn','youth','','what_help','nl','Bel 911 bij direct gevaar, geweld, mishandeling, bedreiging of een andere noodsituatie waarbij politie nodig is.'),
('org_kpcn','youth','','how_to_access','nl','Bel 911 bij spoed of direct gevaar.'),
('org_kpcn','youth','','how_we_help','nl','De politie beoordeelt de situatie en komt in actie wanneer er sprake is van een noodsituatie of direct gevaar.'),
('org_kpcn','youth','','duration','nl','Niet van toepassing.'),
('org_kpcn','youth','','partners','nl',''),
('org_kpcn','youth','','contact','nl','Bel 911 bij spoed of direct gevaar.'),
('org_kpcn','professional','general','organisation_name','nl','Korps Politie Caribisch Nederland (KPCN)'),
('org_kpcn','professional','general','short_description','nl','Korps Politie Caribisch Nederland (KPCN) is de politieorganisatie voor Bonaire, Saba en Sint Eustatius.'),
('org_kpcn','professional','general','target_group','nl','Inwoners, jongeren, ouders, professionals en organisaties die te maken hebben met veiligheid of acute noodsituaties.'),
('org_kpcn','professional','general','support_offer','nl','Politiehulp en noodrespons bij direct gevaar, geweld, bedreiging of andere situaties waarin politie dringend nodig is.'),
('org_kpcn','professional','referral','when_appropriate','nl','Bij spoed, direct gevaar of wanneer dringend politiehulp nodig is.'),
('org_kpcn','professional','referral','criteria','nl','Bel 911 bij spoed of direct gevaar.'),
('org_kpcn','professional','referral','indications_required','nl','Nee.'),
('org_kpcn','professional','practical','contact_details','nl','Bel 911 bij spoed of direct gevaar.'),
('org_guana_chat_918_statia','youth','','who_we_are','en','Guana Chat 918 is a free and anonymous helpline for children and young people.'),
('org_guana_chat_918_statia','youth','','who_for','en','For children and young people who are worried, struggling or need someone to talk to.'),
('org_guana_chat_918_statia','youth','','what_help','en','You can call when you feel sad, afraid, angry or unsure, when something is happening at home or at school, or when you simply need to talk to someone.'),
('org_guana_chat_918_statia','youth','','how_to_access','en','Call 918 free of charge and anonymously.'),
('org_guana_chat_918_statia','youth','','how_we_help','en','You speak with someone who listens and thinks along with you.'),
('org_guana_chat_918_statia','youth','','duration','en','A conversation lasts as long as needed within the contact moment.'),
('org_guana_chat_918_statia','youth','','partners','en',''),
('org_guana_chat_918_statia','youth','','contact','en','Call 918. Website: https://guanachat918.com/'),
('org_guana_chat_918_statia','professional','general','organisation_name','en','Guana Chat 918'),
('org_guana_chat_918_statia','professional','general','short_description','en','Guana Chat 918 is a free and anonymous helpline for children and young people in the Caribbean Netherlands.'),
('org_guana_chat_918_statia','professional','general','target_group','en','Children and young people.'),
('org_guana_chat_918_statia','professional','general','support_offer','en','Free and anonymous phone support for children and young people who need someone to talk to.'),
('org_guana_chat_918_statia','professional','referral','when_appropriate','en','When a child or young person needs a low-threshold, anonymous conversation.'),
('org_guana_chat_918_statia','professional','referral','criteria','en','No formal referral criteria.'),
('org_guana_chat_918_statia','professional','referral','indications_required','en','No. Young people can call directly.'),
('org_guana_chat_918_statia','professional','practical','contact_details','en','Call 918. Website: https://guanachat918.com/'),
('org_guana_chat_918_saba','youth','','who_we_are','en','Guana Chat 918 is a free and anonymous helpline for children and young people.'),
('org_guana_chat_918_saba','youth','','who_for','en','For children and young people who are worried, struggling or need someone to talk to.'),
('org_guana_chat_918_saba','youth','','what_help','en','You can call when you feel sad, afraid, angry or unsure, when something is happening at home or at school, or when you simply need to talk to someone.'),
('org_guana_chat_918_saba','youth','','how_to_access','en','Call 918 free of charge and anonymously.'),
('org_guana_chat_918_saba','youth','','how_we_help','en','You speak with someone who listens and thinks along with you.'),
('org_guana_chat_918_saba','youth','','duration','en','A conversation lasts as long as needed within the contact moment.'),
('org_guana_chat_918_saba','youth','','partners','en',''),
('org_guana_chat_918_saba','youth','','contact','en','Call 918. Website: https://guanachat918.com/'),
('org_guana_chat_918_saba','professional','general','organisation_name','en','Guana Chat 918'),
('org_guana_chat_918_saba','professional','general','short_description','en','Guana Chat 918 is a free and anonymous helpline for children and young people in the Caribbean Netherlands.'),
('org_guana_chat_918_saba','professional','general','target_group','en','Children and young people.'),
('org_guana_chat_918_saba','professional','general','support_offer','en','Free and anonymous phone support for children and young people who need someone to talk to.'),
('org_guana_chat_918_saba','professional','referral','when_appropriate','en','When a child or young person needs a low-threshold, anonymous conversation.'),
('org_guana_chat_918_saba','professional','referral','criteria','en','No formal referral criteria.'),
('org_guana_chat_918_saba','professional','referral','indications_required','en','No. Young people can call directly.'),
('org_guana_chat_918_saba','professional','practical','contact_details','en','Call 918. Website: https://guanachat918.com/'),
('org_kpcn_statia','youth','','who_we_are','en','The Caribbean Netherlands Police Force (KPCN) is the police service for Bonaire, Saba and St. Eustatius.'),
('org_kpcn_statia','youth','','who_for','en','For anyone who sees immediate danger, feels unsafe or urgently needs police assistance.'),
('org_kpcn_statia','youth','','what_help','en','Call 911 in case of immediate danger, violence, abuse, threats or another emergency requiring police assistance.'),
('org_kpcn_statia','youth','','how_to_access','en','Call 911 in an emergency or immediate danger.'),
('org_kpcn_statia','youth','','how_we_help','en','The police assess the situation and respond when there is an emergency or immediate danger.'),
('org_kpcn_statia','youth','','duration','en','Not applicable.'),
('org_kpcn_statia','youth','','partners','en',''),
('org_kpcn_statia','youth','','contact','en','Call 911 in an emergency or immediate danger.'),
('org_kpcn_statia','professional','general','organisation_name','en','Caribbean Netherlands Police Force (KPCN)'),
('org_kpcn_statia','professional','general','short_description','en','KPCN is the police service for Bonaire, Saba and St. Eustatius.'),
('org_kpcn_statia','professional','general','target_group','en','Residents, young people, parents, professionals and organisations dealing with safety or emergency situations.'),
('org_kpcn_statia','professional','general','support_offer','en','Police assistance and emergency response in case of immediate danger, violence, threats or other situations requiring urgent police assistance.'),
('org_kpcn_statia','professional','referral','when_appropriate','en','In case of emergency, immediate danger or urgent need for police assistance.'),
('org_kpcn_statia','professional','referral','criteria','en','Call 911 in an emergency or immediate danger.'),
('org_kpcn_statia','professional','referral','indications_required','en','No.'),
('org_kpcn_statia','professional','practical','contact_details','en','Call 911 in an emergency or immediate danger.'),
('org_kpcn_saba','youth','','who_we_are','en','The Caribbean Netherlands Police Force (KPCN) is the police service for Bonaire, Saba and St. Eustatius.'),
('org_kpcn_saba','youth','','who_for','en','For anyone who sees immediate danger, feels unsafe or urgently needs police assistance.'),
('org_kpcn_saba','youth','','what_help','en','Call 911 in case of immediate danger, violence, abuse, threats or another emergency requiring police assistance.'),
('org_kpcn_saba','youth','','how_to_access','en','Call 911 in an emergency or immediate danger.'),
('org_kpcn_saba','youth','','how_we_help','en','The police assess the situation and respond when there is an emergency or immediate danger.'),
('org_kpcn_saba','youth','','duration','en','Not applicable.'),
('org_kpcn_saba','youth','','partners','en',''),
('org_kpcn_saba','youth','','contact','en','Call 911 in an emergency or immediate danger.'),
('org_kpcn_saba','professional','general','organisation_name','en','Caribbean Netherlands Police Force (KPCN)'),
('org_kpcn_saba','professional','general','short_description','en','KPCN is the police service for Bonaire, Saba and St. Eustatius.'),
('org_kpcn_saba','professional','general','target_group','en','Residents, young people, parents, professionals and organisations dealing with safety or emergency situations.'),
('org_kpcn_saba','professional','general','support_offer','en','Police assistance and emergency response in case of immediate danger, violence, threats or other situations requiring urgent police assistance.'),
('org_kpcn_saba','professional','referral','when_appropriate','en','In case of emergency, immediate danger or urgent need for police assistance.'),
('org_kpcn_saba','professional','referral','criteria','en','Call 911 in an emergency or immediate danger.'),
('org_kpcn_saba','professional','referral','indications_required','en','No.'),
('org_kpcn_saba','professional','practical','contact_details','en','Call 911 in an emergency or immediate danger.');

INSERT INTO organization_profile_answers (organization_id, audience_code, group_key, field_key, language_code, answer_text, translation_status, source_locked)
SELECT o.id, p.audience_code, p.group_key, p.field_key, p.language_code, p.answer_text, 'reviewed', 1
FROM tmp_profile_polish p
JOIN organizations o ON o.external_key = p.external_key
ON DUPLICATE KEY UPDATE
  answer_text = VALUES(answer_text),
  translation_status = VALUES(translation_status),
  source_locked = VALUES(source_locked);

CREATE TEMPORARY TABLE IF NOT EXISTS tmp_keyword_polish (external_key VARCHAR(120), language_code VARCHAR(8), keyword VARCHAR(190));
TRUNCATE tmp_keyword_polish;
INSERT INTO tmp_keyword_polish (external_key, language_code, keyword) VALUES
('org_eoz','nl','Expertisecenter Onderwijs en Zorg (EOZ)'),
('org_eoz','nl','Expertisecenter Onderwijs Zorg Bonaire (EOZ)'),
('org_eoz','nl','expertisecenter onderwijs en zorg'),
('org_eoz','nl','EOZ'),
('org_ggd_bonaire','nl','zwanger'),
('org_ggd_bonaire','nl','zwangerschap'),
('org_ggd_bonaire','nl','zwangerschapsbegeleiding'),
('org_ggd_bonaire','nl','kinderwens'),
('org_ggd_bonaire','nl','anticonceptie'),
('org_ggd_bonaire','nl','soa'),
('org_ggd_bonaire','nl','SOA-test'),
('org_ggd_bonaire','nl','seksuele gezondheid'),
('org_ggd_bonaire','nl','prep'),
('org_ggd_bonaire','nl','reizigersspreekuur'),
('org_ggd_bonaire','nl','vaccinatie'),
('org_ggd_bonaire','nl','vaccinaties'),
('org_ggd_bonaire','nl','jeugdgezondheidszorg'),
('org_ggd_bonaire','nl','JGZ'),
('org_ggd_bonaire','nl','consultatiebureau'),
('org_ggd_bonaire','nl','Mi Futuro'),
('org_ggd_bonaire','nl','Mi Eskoho'),
('org_ggd_bonaire','nl','Mi Futuro Mi Eskoho Konsiente'),
('org_ggd_bonaire','nl','Nu Niet Zwanger'),
('org_ggd_bonaire','nl','NNZ'),
('org_ggd_bonaire','nl','Bon Salu'),
('org_ggd_bonaire','nl','Resilensia'),
('org_fkpd','nl','beperking'),
('org_fkpd','nl','handicap'),
('org_fkpd','nl','verstandelijke beperking'),
('org_fkpd','nl','lichamelijke beperking'),
('org_fkpd','nl','dagopvang'),
('org_fkpd','nl','naschoolse opvang'),
('org_fkpd','nl','pasadia'),
('org_fkpd','nl','zelfredzaamheid'),
('org_fkpd','nl','begeleiding beperking'),
('org_fkpd','nl','ZODIEZIJN'),
('org_fundashon_forma','nl','diploma'),
('org_fundashon_forma','nl','startkwalificatie'),
('org_fundashon_forma','nl','entree'),
('org_fundashon_forma','nl','entreeopleiding'),
('org_fundashon_forma','nl','mbo 1'),
('org_fundashon_forma','nl','ALFA'),
('org_fundashon_forma','nl','laaggeletterd'),
('org_fundashon_forma','nl','lezen'),
('org_fundashon_forma','nl','schrijven'),
('org_fundashon_forma','nl','taal'),
('org_fundashon_forma','nl','LLL'),
('org_fundashon_forma','nl','Long Life Learning'),
('org_fundashon_forma','nl','VSO'),
('org_fundashon_forma','nl','werk'),
('org_fundashon_forma','nl','opleiding'),
('org_fundashon_forma','nl','arbeidsvaardigheden'),
('org_rosa_di_sharon','nl','KHF'),
('org_rosa_di_sharon','nl','Kas pa Hoben ku Futuro'),
('org_rosa_di_sharon','nl','Rosa di Sharon'),
('org_rosa_di_sharon','nl','Fundashon Rosa di Sharon'),
('org_rosa_di_sharon','nl','tienermeisje'),
('org_rosa_di_sharon','nl','tienermeisjes'),
('org_rosa_di_sharon','nl','zwangere tiener'),
('org_rosa_di_sharon','nl','zwangere tieners'),
('org_rosa_di_sharon','nl','jonge moeder'),
('org_rosa_di_sharon','nl','jonge moeders'),
('org_rosa_di_sharon','nl','zwanger'),
('org_rosa_di_sharon','nl','woonvoorziening'),
('org_rosa_di_sharon','nl','24-uurs woonbegeleiding'),
('org_rosa_di_sharon','nl','begeleid wonen'),
('org_rosa_di_sharon','nl','Kaminda Nieuw Amsterdam'),
('org_zjcn','nl','opvoedhulp'),
('org_zjcn','nl','opvoedondersteuning'),
('org_zjcn','nl','pleegzorg'),
('org_zjcn','nl','begeleid wonen'),
('org_zjcn','nl','BWB'),
('org_zjcn','nl','Famia Fuerte'),
('org_zjcn','nl','kindermishandeling'),
('org_zjcn','nl','huiselijk geweld'),
('org_zjcn','nl','jeugdproblematiek'),
('org_zjcn','nl','gezinsondersteuning'),
('org_zjcn','nl','jeugdzorg'),
('org_mhc','nl','Hi-5'),
('org_mhc','nl','angst'),
('org_mhc','nl','somber'),
('org_mhc','nl','somberheid'),
('org_mhc','nl','depressie'),
('org_mhc','nl','boosheid'),
('org_mhc','nl','trauma'),
('org_mhc','nl','hechting'),
('org_mhc','nl','gaming'),
('org_mhc','nl','verslaving'),
('org_mhc','nl','alcohol'),
('org_mhc','nl','drugs'),
('org_mhc','nl','psycholoog'),
('org_mhc','nl','kinderpsychiater'),
('org_reclassering_cn','nl','jeugdreclassering'),
('org_reclassering_cn','nl','strafbaar feit'),
('org_reclassering_cn','nl','politie'),
('org_reclassering_cn','nl','rechter'),
('org_reclassering_cn','nl','OM'),
('org_reclassering_cn','nl','Openbaar Ministerie'),
('org_reclassering_cn','nl','leerplicht'),
('org_reclassering_cn','nl','schoolverzuim'),
('org_reclassering_cn','nl','proces-verbaal'),
('org_reclassering_cn','nl','justitie'),
('org_reclassering_cn','nl','JoVo'),
('org_voogdijraad_cn','nl','HALT'),
('org_voogdijraad_cn','nl','Halt'),
('org_voogdijraad_cn','nl','kinderalimentatie'),
('org_voogdijraad_cn','nl','alimentatie'),
('org_voogdijraad_cn','nl','gezag'),
('org_voogdijraad_cn','nl','omgang'),
('org_voogdijraad_cn','nl','raadsonderzoek'),
('org_voogdijraad_cn','nl','kinderbescherming'),
('org_voogdijraad_cn','nl','bijzonder curator'),
('org_voogdijraad_cn','nl','centrale autoriteit'),
('org_voogdijraad_cn','nl','schoolverzuim'),
('org_jong_bonaire','nl','naschoolse activiteiten'),
('org_jong_bonaire','nl','naschoolse opvang'),
('org_jong_bonaire','nl','sport'),
('org_jong_bonaire','nl','cultuur'),
('org_jong_bonaire','nl','talentontwikkeling'),
('org_jong_bonaire','nl','zomerkamp'),
('org_jong_bonaire','nl','zomerkampen'),
('org_jong_bonaire','nl','middelbare school'),
('org_jong_bonaire','nl','voortgezet onderwijs'),
('org_jong_bonaire','nl','12 tot 18'),
('org_jong_bonaire','nl','jongerenwerk'),
('org_guana_chat_918','nl','918'),
('org_guana_chat_918','nl','Guana Chat'),
('org_guana_chat_918','nl','guanachat'),
('org_guana_chat_918','nl','hulplijn'),
('org_guana_chat_918','nl','kindertelefoon'),
('org_guana_chat_918','nl','anoniem'),
('org_guana_chat_918','nl','gratis bellen'),
('org_guana_chat_918','nl','praten'),
('org_guana_chat_918','nl','directe hulp'),
('org_kpcn','nl','politie'),
('org_kpcn','nl','KPCN'),
('org_kpcn','nl','911'),
('org_kpcn','nl','noodnummer'),
('org_kpcn','nl','noodsituatie'),
('org_kpcn','nl','direct gevaar'),
('org_kpcn','nl','geweld'),
('org_kpcn','nl','bedreiging'),
('org_kpcn','nl','veiligheid'),
('org_zjcn_statia','en','youth care'),
('org_zjcn_statia','en','parenting support'),
('org_zjcn_statia','en','foster care'),
('org_zjcn_statia','en','supported living'),
('org_zjcn_statia','en','child abuse'),
('org_zjcn_statia','en','domestic violence'),
('org_zjcn_statia','en','family support'),
('org_zjcn_statia','en','youth problems'),
('org_zjcn_saba','en','youth care'),
('org_zjcn_saba','en','parenting support'),
('org_zjcn_saba','en','foster care'),
('org_zjcn_saba','en','supported living'),
('org_zjcn_saba','en','child abuse'),
('org_zjcn_saba','en','domestic violence'),
('org_zjcn_saba','en','family support'),
('org_zjcn_saba','en','youth problems'),
('org_mhc_statia','en','Hi-5'),
('org_mhc_statia','en','anxiety'),
('org_mhc_statia','en','sadness'),
('org_mhc_statia','en','depression'),
('org_mhc_statia','en','anger'),
('org_mhc_statia','en','trauma'),
('org_mhc_statia','en','attachment'),
('org_mhc_statia','en','gaming'),
('org_mhc_statia','en','addiction'),
('org_mhc_statia','en','alcohol'),
('org_mhc_statia','en','drugs'),
('org_mhc_statia','en','psychologist'),
('org_mhc_statia','en','child psychiatrist'),
('org_mhc_saba','en','Hi-5'),
('org_mhc_saba','en','anxiety'),
('org_mhc_saba','en','sadness'),
('org_mhc_saba','en','depression'),
('org_mhc_saba','en','anger'),
('org_mhc_saba','en','trauma'),
('org_mhc_saba','en','attachment'),
('org_mhc_saba','en','gaming'),
('org_mhc_saba','en','addiction'),
('org_mhc_saba','en','alcohol'),
('org_mhc_saba','en','drugs'),
('org_mhc_saba','en','psychologist'),
('org_mhc_saba','en','child psychiatrist'),
('org_voogdijraad_statia','en','HALT'),
('org_voogdijraad_statia','en','child maintenance'),
('org_voogdijraad_statia','en','guardianship'),
('org_voogdijraad_statia','en','contact arrangements'),
('org_voogdijraad_statia','en','child protection'),
('org_voogdijraad_statia','en','special curator'),
('org_voogdijraad_statia','en','central authority'),
('org_voogdijraad_statia','en','truancy'),
('org_voogdijraad_saba','en','HALT'),
('org_voogdijraad_saba','en','child maintenance'),
('org_voogdijraad_saba','en','guardianship'),
('org_voogdijraad_saba','en','contact arrangements'),
('org_voogdijraad_saba','en','child protection'),
('org_voogdijraad_saba','en','special curator'),
('org_voogdijraad_saba','en','central authority'),
('org_voogdijraad_saba','en','truancy'),
('org_guana_chat_918_statia','en','918'),
('org_guana_chat_918_statia','en','Guana Chat'),
('org_guana_chat_918_statia','en','guanachat'),
('org_guana_chat_918_statia','en','helpline'),
('org_guana_chat_918_statia','en','child helpline'),
('org_guana_chat_918_statia','en','anonymous'),
('org_guana_chat_918_statia','en','free call'),
('org_guana_chat_918_statia','en','talk'),
('org_guana_chat_918_statia','en','direct help'),
('org_guana_chat_918_saba','en','918'),
('org_guana_chat_918_saba','en','Guana Chat'),
('org_guana_chat_918_saba','en','guanachat'),
('org_guana_chat_918_saba','en','helpline'),
('org_guana_chat_918_saba','en','child helpline'),
('org_guana_chat_918_saba','en','anonymous'),
('org_guana_chat_918_saba','en','free call'),
('org_guana_chat_918_saba','en','talk'),
('org_guana_chat_918_saba','en','direct help'),
('org_kpcn_statia','en','police'),
('org_kpcn_statia','en','KPCN'),
('org_kpcn_statia','en','911'),
('org_kpcn_statia','en','emergency number'),
('org_kpcn_statia','en','emergency'),
('org_kpcn_statia','en','immediate danger'),
('org_kpcn_statia','en','violence'),
('org_kpcn_statia','en','threat'),
('org_kpcn_statia','en','safety'),
('org_kpcn_saba','en','police'),
('org_kpcn_saba','en','KPCN'),
('org_kpcn_saba','en','911'),
('org_kpcn_saba','en','emergency number'),
('org_kpcn_saba','en','emergency'),
('org_kpcn_saba','en','immediate danger'),
('org_kpcn_saba','en','violence'),
('org_kpcn_saba','en','threat'),
('org_kpcn_saba','en','safety');

INSERT INTO organization_keywords (organization_id, language_code, keyword)
SELECT o.id, k.language_code, k.keyword
FROM tmp_keyword_polish k
JOIN organizations o ON o.external_key = k.external_key
ON DUPLICATE KEY UPDATE keyword = VALUES(keyword);

DROP TEMPORARY TABLE IF EXISTS tmp_profile_polish;
DROP TEMPORARY TABLE IF EXISTS tmp_keyword_polish;

COMMIT;
